apiVersion: v1
kind: DeploymentConfig
metadata:
  name: mb-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: Rolling
  template:
    metadata:
      labels:
        deployment: mb
    spec:
      containers:
      - name: mb
        image: wso2brasil/wso2ei-mb-6.4.0:v1
        imagePullPolicy: Always
        ports:
        -
          containerPort: 5675
          protocol: "TCP"
        -
          containerPort: 9446
          protocol: "TCP"
        -
          containerPort: 9766
          protocol: TCP

