apiVersion: v1
kind: DeploymentConfig
metadata:
  name: wso2mb-deployment-anupam
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: Rolling
  template:
    metadata:
      labels:
        deployment: mb-anupam
    spec:
      containers:
      - name: mb-anupam
        image: wso2brasil/wso2ei-mb-6.4.0:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        ports:
        -
          containerPort: 5675
          protocol: "TCP"
        -
          containerPort: 9446
          protocol: "TCP"
        -
          containerPort: 9766
          protocol: TCP

