apiVersion: v1
kind: Service
metadata:
  name: mb-service
spec:
  selector:
    deploymentconfig: mb-deployment
  ports:
  -
    name: servlet-http
    protocol: TCP
    port: 9766
    targetPort: 9766
  -
    name: servlet-https
    protocol: TCP
    port: 9446
    targetPort: 9446
  -
    name: amqp-http
    protocol: TCP
    port: 5675
    targetPort: 5675