apiVersion: v1
kind: DeploymentConfig
metadata:
  name: pizza-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: Rolling
  template:
    metadata:
      labels:
        deployment: pizza
    spec:
      containers:
      - name: pizza
        image: 172.30.1.1:5000/wso2/pizza-app:1.0.0
        imagePullPolicy: Never
        ports:
        -
          containerPort: 8081
          protocol: "TCP"
