apiVersion: v1
kind: DeploymentConfig
metadata:
  name: wso2ei-deployment-anupam
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: Rolling
  template:
    metadata:
      labels:
        deployment: ei-anupam
    spec:
      containers:
        - name: ei-anupam
          image: wso2brasil/wso2ei-integrator-6.4.0:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          ports:
            -
              containerPort: 8280
              protocol: "TCP"
            -
              containerPort: 8243
              protocol: "TCP"
            -
              containerPort: 9763
              protocol: TCP
            -
              containerPort: 9443
              protocol: TCP
