apiVersion: v1
kind: Service
metadata:
  name: wso2ei-service-anupam
spec:
  selector:
    deploymentconfig: wso2ei-deployment-anupam
  type: LoadBalancer
  ports:
    -
      name: servlet-http
      protocol: TCP
      port: 9763
      targetPort: 9763
    -
      name: servlet-https
      protocol: TCP
      port: 9443
      targetPort: 9443
    -
      name: gw-http
      protocol: TCP
      port: 8280
      targetPort: 8280
    -
      name: gw-https
      protocol: TCP
      port: 8243
      targetPort: 8243