apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: wso2
            - name: POSTGRES_PASSWORD
              value: wso2
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: init-data
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-data
          configMap:
            name: init-data
