apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-xe-deployment
  labels:
    app: oracle-xe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-xe
  template:
    metadata:
      labels:
        app: oracle-xe
    spec:
      containers:
        - name: oracle-xe
          image: oracle-xe:18c
          ports:
            - containerPort: 1521
              protocol: TCP
