apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: mysql-port
    port: 3306
    targetPort: 3306
    protocol: TCP