apiVersion: v1
kind: DeploymentConfig
metadata:
  name: is-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: Rolling
  template:
    metadata:
      labels:
        deployment: is
    spec:
      containers:
      - name: is
        image: 172.30.1.1:5000/wso2/is
        imagePullPolicy: Never
#        securityContext:
#          runAsUser: 802
        ports:
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"
        volumeMounts:
        - name: config-carbon
          mountPath: /home/wso2carbon/wso2is-5.7.0/repository/conf/carbon.xml
          subPath: carbon.xml
      serviceAccountName: "wso2svc-account"
      volumes:
      - name: config-carbon
        configMap:
          name: config-carbon
