apiVersion: v1
kind: Route
metadata:
  name: wso2is-as-km
spec:
  host: XX_IS_HOST_NAME_XX
  port:
    targetPort: servlet-https
  to:
    kind: Service
    name: is-service
  tls:
    termination: passthrough