apiVersion: v1
kind: Service
metadata:
  name: apim-service
spec:
  selector:
    app: apim
  ports:
  - name: servlet-http
    port: 9763
    targetPort: 9763
    protocol: TCP
  - name: servlet-https
    port: 9443
    targetPort: 9443
    protocol: TCP
  - name: gw-http
    port: 8280
    targetPort: 8280
    protocol: TCP
  - name: gw-https
    port: 8243
    targetPort: 8243
    protocol: TCP
